name: nq
version: "2.5.11"
license: "GPL-2.0-or-later"
date: 2024-01-12
description: |
    Nilpotent Quotients of Finitely Presented Groups

authors:
    - name: Werner Nickel
      url: http://www.mathematik.tu-darmstadt.de/~nickel/

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.9"

needed-pkgs:
    - name: "polycyclic"
      version: "2.11"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://gap-packages.github.io/nq/
readme: README.md
packageinfo: https://gap-packages.github.io/nq/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/nq/releases/download/v2.5.11/nq-2.5.11.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/nq/releases/download/v2.5.11/nq-2.5.11.tar.bz2

abstract: |
    This package provides access to the ANU nilpotent quotient program for computing nilpotent factor groups of finitely presented groups.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    nilpotent quotient algorithm, nilpotent presentations, finitely presented groups, finite presentations   , commutators, lower central series, identical relations, expression trees, nilpotent Engel groups, right and left Engel elements, computational.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HN24</span>]   <b class='BibAuthor'>Horn, M. and Nickel, W.</b>,
     <i class='BibTitle'>nq, Nilpotent Quotients of Finitely Presented Groups,
             Version 2.5.11</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/nq/">https://gap-packages.github.io/nq/</a></span>.
    </p>
    

bibtex: |
    @misc{ nq2.5.11,
      author =           {Horn, M. and Nickel, W.},
      title =            {{nq},   Nilpotent   Quotients  of  Finitely  Presented
                          Groups, {V}ersion 2.5.11},
      month =            {Jan},
      year =             {2024},
      note =             {Refereed GAP package},
      howpublished =     {\href             {https://gap-packages.github.io/nq/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{nq/}}},
      keywords =         {nilpotent quotient algorithm; nilpotent presentations;
                          finitely  presented  groups;  finite  presentations  ;
                          commutators;    lower    central   series;   identical
                          relations;  expression  trees; nilpotent Engel groups;
                          right and left Engel elements; computational},
      printedkey =       {HN24}
    }

