name: nq
version: 2.5.9
date: 2022-10-26
description: |
    Nilpotent Quotients of Finitely Presented Groups

authors:
    - name: Werner Nickel
      url: http://www.mathematik.tu-darmstadt.de/~nickel/

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.9"

needed-pkgs:
    - name: "polycyclic"
      version: "2.11"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://gap-packages.github.io/nq/
readme: README.md
packageinfo: https://gap-packages.github.io/nq/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/nq/releases/download/v2.5.9/nq-2.5.9.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/nq/releases/download/v2.5.9/nq-2.5.9.tar.bz2

abstract: |
    This package provides access to the ANU nilpotent quotient program for computing nilpotent factor groups of finitely presented groups.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
