##############################################################################
##
##    Makefile                      NQ                         Werner Nickel
##
##    $Id$
##
manual:
	tex manual
	tex manual

clean:
	rm -f manual.aux manual.dvi manual.idx manual.log 

spotless: clean
	rm -f manual.lab manual.six manual.toc manual.tex
